
home:
    url: /admin/
    action: Home

error_500:
    url: /admin/error_500
    action: Admin:error_500

lock_screen:
    url: /admin/locked
    action: Home:lock_screen

login:
    url: /admin/login
    action: Home:login
	
logout:
    url: /admin/logout
    action: Home:logout
	
dashboard:
    url: /admin/dashboard
    action: Home:dashboard

channel:
    url: /admin/channel/:id
    action: Channels:list_channel

node_edit:
    url: /admin/node_edit/:id
    action: Nodes:edit_node

fields_groups:
    url: /admin/fields_groups
    action: Custom_fields:show_groups

add_field_groups:
    url: /admin/add_field_group
    action: Custom_fields:add_group

edit_field_group:
    url: /admin/edit_field_group/:id
    action: Custom_fields:edit_group

custom_fields:
    url: /admin/custom_fields/:id
    action: Custom_fields:show_fields

add_custom_field:
    url: /admin/add_custom_field/:id
    action: Custom_fields:add_custom_field

edit_custom_field:
    url: /admin/edit_custom_field/:id
    action: Custom_fields:edit_custom_field

manage_channels:
    url: /admin/manage_channels
    action: Channels:manage_channels
