
# Error pages

error_500:
    url: /admin/error_500
    action: Admin:error_500



# First pages

home:
    url: /admin/
    action: Home

lock_screen:
    url: /admin/locked
    action: Home:lock_screen

login:
    url: /admin/login
    action: Home:login
	
logout:
    url: /admin/logout
    action: Home:logout
	
dashboard:
    url: /admin/dashboard
    action: Home:dashboard



# Channels 

manage_channels:
    url: /admin/manage_channels
    action: Channels:manage_channels

add_channel:
    url: /admin/add_channel
    action: Channels:add_channel

edit_channel:
    url: /admin/edit_channel/:id
    action: Channels:edit_channel

delete_channel:
    url: /admin/delete_channel/:id
    action: Channels:delete_channel



# Nodes

channel:
    url: /admin/channel/:id
    action: Channels:list_channel

node_add:
    url: /admin/node_add/:channel
    action: Nodes:add_node

node_edit:
    url: /admin/node_edit/:id
    action: Nodes:edit_node

node_delete:
    url: /admin/node_delete/:id
    action: Nodes:delete_node




# Custom fields groups 

fields_groups:
    url: /admin/fields_groups
    action: Custom_fields:show_groups

fields_group_add:
    url: /admin/add_field_group
    action: Custom_fields:add_group

fields_group_edit:
    url: /admin/edit_field_group/:id
    action: Custom_fields:edit_group

fields_group_delete:
    url: /admin/delete_field_group/:id
    action: Custom_fields:delete_group



# Custom fields

custom_fields:
    url: /admin/custom_fields/:id
    action: Custom_fields:show_fields

custom_field_add:
    url: /admin/add_custom_field/:id
    action: Custom_fields:add_custom_field

custom_field_edit:
    url: /admin/edit_custom_field/:id
    action: Custom_fields:edit_custom_field

custom_field_delete:
    url: /admin/delete_custom_field/:id
    action: Custom_fields:detele_custom_field



# Settings

settings:
    url: /admin/settings
    action: Settings:show_settings

security:
    url: /admin/settings/security
    action: Settings:security



# users

users:
    url: /admin/users
    action: Users:show_users

user_roles:
    url: /admin/user_roles
    action: Users:user_roles

user_edit:
    url: /admin/user_edit/:id
    action: Users:user_edit

role_edit:
    url: /admin/user_roles/role_edit/:id
    action: Users:role_edit

role_add:
    url: /admin/user_roles/role_add
    action: Users:role_add

role_delete:
    url: /admin/user_roles/role_delete/:id
    action: Users:role_delete



# Components

components:
    url: /admin/components
    action: Components:show_components
	
component_install:
    url: /admin/component_install/:component
    action: Components:install_component
	
component_uninstall:
    url: /admin/component_uninstall/:component
    action: Components:uninstall_component

component_action:
    url: /admin/component/:component/:class/:action
    action: Components:component_action