
home:
    url: /
    action: Home

error_500:
    url: /error_500
    action: Home:error_500

login:
    url: /login
    action: Home:login
	
logout:
    url: /logout
    action: Home:logout
	
dashboard:
    url: /dashboard
    action: Home:dashboard
	
users:
    url: /users
    action: Users:view_all

user_add:
    url: /users/add
    action: Users:add_user

user_edit:
    url: /users/edit/:id
    action: Users:edit_user

user_delete:
    url: /users/delete/:id
    action: Users:delete_user
	
projects:
    url: /projects
    action: Projects:view_all

project_add:
    url: /projects/add
    action: Projects:add_project

project_edit:
    url: /projects/edit/:id
    action: Projects:edit_project

project_delete:
    url: /projects/delete/:id
    action: Projects:delete_project

project_view:
    url: /project/:id
    action: Projects:view_one

task_add:
    url: /projects/task_add/:id
    action: Projects:task_add

task_edit:
    url: /projects/task_edit/:id
    action: Projects:task_edit

task_delete:
    url: /projects/task_delete/:id
    action: Projects:task_delete

task_view:
    url: /task/:id
    action: Projects:task_view

log_time:
    url: /task/:id/log_time
    action: Projects:log_time
