
home:
    url: /admin/
    action: Home

error_500:
    url: /admin/error_500
    action: Admin:error_500

lock_screen:
    url: /admin/locked
    action: Home:lock_screen

login:
    url: /admin/login
    action: Home:login
	
logout:
    url: /admin/logout
    action: Home:logout
	
dashboard:
    url: /admin/dashboard
    action: Home:dashboard

channel:
    url: /admin/channel/:id
    action: Channels:list_channel

node_edit:
    url: /admin/node_edit/:id
    action: Nodes:edit_node
